### ISSUE TITLE
audio_sample_rate does not exist on ytdl.videoFormat

### ISSUE THREAD

**Issue by Favna** [amishshah/ytdl-core-discord#10]
In your filter function you use `format.audio_sample_rate`:

https://github.com/amishshah/ytdl-core-discord/blob/4348b4a2d2761a9f19d60db765ffe1c5fd861a6c/index.js#L7

However this property does not exist on `videoFormat`, which is the proper typing for format in this instance: [See typings here](https://github.com/fent/node-ytdl-core/blob/ce071d7b06ff0f5932dde086b701b3af06697c4f/typings/index.d.ts#L21)

What you likely meant instead is `audioBitrate`:

![image](https://user-images.githubusercontent.com/4019718/54082827-7f464380-431b-11e9-89d0-a2fff037f56b.png)

**Comment by iCrawl** [comment]
https://github.com/fent/node-ytdl-core/blob/master/example/info.json

CTRL+F: "audio_sample_rate", 5 hits, all accurate 
![image](https://user-images.githubusercontent.com/20760160/54083098-b74f8580-431f-11e9-80ea-9351be0f3c56.png)
![image](https://user-images.githubusercontent.com/20760160/54083101-bcacd000-431f-11e9-82ef-d1e3f1534c8d.png)

**Comment by Favna** [comment]
Ah.. well.. fair nuf. Guess I'll just extend ytdl-core's VideoFormat adding this prop then.
