### ISSUE TITLE
Bot joins and plays nothing for videos without webm + opus

### ISSUE THREAD

**Issue by Taha-Chaudhry** [amishshah/ytdl-core-discord#114]
When my bot tries to play a video that has 'webm + opus' codec, it plays fine, but when i try to play a different one without the codec, it just joins the channel and plays nothing. I assumed this was because of not having ffmpeg, but i double checked and i had it. 

I've also noticed that it still says it still has `message.guild.voiceConnection` even when it's not playing anything. 

Here's my code to play the video:

`      server.dispatcher = connection.playOpusStream(
          await dytdl(server.queue[0]).catch(console.log),
          { highWaterMark: 1 }
        );`

**Comment by sudormr** [comment]
This sounds like an issue with vorbis, youtube uses vorbis for some videos but it's rare.

**Comment by Taha-Chaudhry** [comment]
is there any way to fix that? Like maybe have a vorbis interpreter to opus or something?

**Comment by sudormr** [comment]
It's possible.

**Comment by Taha-Chaudhry** [comment]
I can't seem to change the volume of the connection, or pause or resume it. Can anyone try and replicate this?

**Comment by Taha-Chaudhry** [comment]
> For videos where the required codec (webm + opus) isn't available, the module will fallback to using FFmpeg to encode the stream in Opus

that's what it says on the package information, but it doesn't seem to be doing that ever

**Comment by Taha-Chaudhry** [comment]
Fixed with the latest update
