### ISSUE TITLE
Error: This video is unavailable.

### ISSUE THREAD

**Issue by EltonAU** [amishshah/ytdl-core-discord#121]
Hi, trying to play this video -> https://www.youtube.com/watch?v=erPNRUjwg_g with ytdl-core-discord, but every time I play it, I get an error saying "Error: This video is unavailable". Here is the piece of code that play the video.

`let connection = await queue[0].voiceChannel.join()
const dispatcher = connection.play(await ytdl(queue[0].url), {type: 'opus'});`

This only happens on this video so far. I switched to ytdl-core-discord because it fixed a weird problem I had with ytdl-core that stopped the stream randomly on long videos (1+ hour), but then I found this new problem. Thank you for your help!

**Comment by advaith1** [comment]
I'm also getting this issue for many videos.

**Comment by EltonAU** [comment]
It seems that I was using the old version by using 'npm install ytdl-core-discord'. This version is still using ytdl-core v0.29 or something, which is outdated.

I fixed it by using 'npm install https://github.com/amishshah/ytdl-core-discord'.


> I'm also getting this issue for many videos, including the one provided above.

See if you are using the wrong version and try to update the library to the github version.

**Comment by amishshah** [comment]
A new version has now been released.
