### ISSUE TITLE
Please update NPM package

### ISSUE THREAD

**Issue by kyletuite** [amishshah/ytdl-core-discord#136]
Currently, the NPM package is @ version 1.0.3, but the package.json is still using ytdl-core@0.29.1. In order to use ytdl-cord-discord you have to pull from this repository, manually place the folder in node_modules, then run 'npm i' from the module directory to get it work.

It would be greatly appreciated if the NPM package could be updated to reflect the actual current version. Otherwise it will return:

`Error: Cannot find module 'm3u8stream/lib/parse-time'`

And the application won't start.

**Comment by amishshah** [comment]
Updated to [`v1.1.0`](https://github.com/amishshah/ytdl-core-discord/tree/v1.1.0)

**Comment by kyletuite** [comment]
> 
> 
> Updated to [`v1.1.0`](https://github.com/amishshah/ytdl-core-discord/tree/v1.1.0)

Much appreciated! I know I could have `npm i` with the repository link, but this is really helpful! Thanks, @amishshah! This and the Prism-media projects are fantastic, and yours, and your collaborators' work is very much appreciated!
