### ISSUE TITLE
Discord.JS dispatcher fires early for songs with 3-4 mins length

### ISSUE THREAD

**Issue by LordDamionDevil** [amishshah/ytdl-core-discord#148]
I have noticed that the dispatcher.on("end") fires early for songs above 3-4 mins

**Comment by ggonzalezh** [comment]
I'm also getting this issue.

**Comment by LordDamionDevil** [comment]
Turned out it had something to do with ytdl-core and the solution with the highwatermark on this thread fixed it.
https://github.com/fent/node-ytdl-core/issues/402

```
const dispatcher = connection.playOpusStream(await ytdl(url, {
		filter: "audioonly",
		highWaterMark: 1<<25
	}))
```
