### ISSUE TITLE
Update ytdl-core please.

### ISSUE THREAD

**Issue by xjulianCodes** [amishshah/ytdl-core-discord#160]
Please update to ytdl-core@2.0.1

**Comment by jacobgc** [comment]
There's a pull request already in for it, just needs accepting :)

**Comment by North-West-Wind** [comment]
The old ytdl-core is causing some errors. I also hope they will update ytdl-core in this project or else I might have to download this whole thing and just change that little bit of stuff.

**Comment by jacobgc** [comment]
Issue fixed in 3ee5182a4f201e97eff6d79a7ae63d726cf35afb

**Comment by North-West-Wind** [comment]
Nice
