### ISSUE TITLE
TypeScript: property 'type' does not exist

### ISSUE THREAD

**Issue by SyntleLmao** [amishshah/ytdl-core-discord#168]
I used the following discord.js v12 example:
```js
connection.play(await ytdl(url), { type: 'opus' });
```
And got the following error:
```
Object literal may only specify known properties, and 'type' does not exist in type 'downloadOptions'.
```
This issue only seems to occur when I import using `import`:
`import ytdl from 'ytdl-core-discord'`

**Comment by amishshah** [comment]
Are you sure you aren't doing `ytdl(url, { type: 'opus' })`? Because that's what the error suggests to me

**Comment by SyntleLmao** [comment]
Easy mistake to make, sorry about that.
