### ISSUE TITLE
question

### ISSUE THREAD

**Issue by YinglunQ** [amishshah/ytdl-core-discord#183]
Hi. I am wondering what would be the proper way to stream live youtube video using the package. When I tried it, the stream would just end and no errors would appear. It doesn't happen to normal videos. Any help is appreciated thanks!

**Comment by MrZBou** [comment]
If you have `filter: audioonly`, then the problem is this. Live videos do not play with this filter, so you can change this to `audioandvideo` for live videos.

**Comment by YinglunQ** [comment]
@MrZBou thank you for the tip!
