### ISSUE TITLE
ytdl-core events

### ISSUE THREAD

**Issue by JMTK** [amishshah/ytdl-core-discord#201]
Hello,

I've tried testing this multiple ways. Right now I don't think it's possible to do the equivalent of 
```
let ytstream = ytdl(url);

ytstream.on('info', function(infoObj) {

});
```
[Reference](https://github.com/fent/node-ytdl-core#event-info) 

Would code that looks like this need to be changed to use the `getInfo` function instead?

**Comment by boraarslan** [comment]
Same issue here. Cant listen any type of event from stream object.

**Comment by amishshah** [comment]
@JMTK yes, you would need to use getInfo for this.
