### ISSUE TITLE
this npm module does not work. 

### ISSUE THREAD

**Issue by shakylol** [amishshah/ytdl-core-discord#202]
using the exact same code, i switched from the ytdl-core-discord module, which wasnt working, to the ytdl-core module, again, with the exact same code, and everything worked fine

**Comment by tyliec** [comment]
Make sure you define your functions as async, that's where I went wrong at first.

**Comment by UnbreakCode** [comment]
Doesn't work for me either

(node:5448) UnhandledPromiseRejectionWarning: Error [VOICE_PLAY_INTERFACE_BAD_TYPE]: Unknown stream type
    at VoiceConnection.play (C:\Users\Niclas\Desktop\MusicBot\node_modules\discord.js\src\client\voice\util\PlayInterface.js:84:11)
    at C:\Users\Niclas\Desktop\MusicBot\indexREAL.js:113:27
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by UnbreakCode** [comment]
had the same issue even with an async fuction. after adding await it worked.
for example: dispatcher = connection.play(await stream, { type: 'opus' });
