### ISSUE TITLE
ytdl-core-discord error

### ISSUE THREAD

**Issue by Ironrescue** [amishshah/ytdl-core-discord#217]
i tried to add ytdl-core-discord to const ytdl but when I tried to play music here's what it says: [VOICE PLAY INTERFACE BAD_TYPE]: Unknown stream type

**Comment by Ironrescue** [comment]
> i tried to add ytdl-core-discord to const ytdl but when I tried to play music here's what it says: [VOICE PLAY INTERFACE BAD_TYPE]: Unknown stream type

**Comment by Ironrescue** [comment]
> i tried to add ytdl-core-discord to const ytdl but when I tried to play music here's what it says: [VOICE PLAY INTERFACE BAD_TYPE]: Unknown stream type

**Comment by amishshah** [comment]
This is an issue for the discord.js repository, please also attach the code you are using there.

**Comment by eryon** [comment]
@Ironrescue this happened to me when I didn't `await` the response from `ytdl` to resolve the url. Easy mistake to make, just forgot about it.

**Incorrect:**
```js
server.voiceConnection.play(ytdl(song.url))
```

**Correct:**
```js
server.voiceConnection.play(await ytdl(song.url))
```
