### ISSUE TITLE
 YouTube Compliance Issues & Help

### ISSUE THREAD

**Issue by suhd00d** [amishshah/ytdl-core-discord#221]
Hi there,
I got an email from YouTube stating that this is not in compliance with them due to the fact that we store data for 12 months. Can you please help me find the code so I can change it from 12 months to 30 days? The report is pasted below. I have 15 days to fix the issue or they won't remove the IP ban.

July 27, 2020
ToS Violations Report V.1 YouTube API Services-Developer Policies
Violations that require immediate resolution:
E. Handling YouTube Data and Content (l​ ink​)
Policy #​: III.E.4.a-g​ (Refreshing, Storing, and Displaying API Data) (​link​)
● Violation: ​API Client is storing data for more than 30 days.
Proposed Solution: ​Regarding data storage, we only allow the API Clients to store the public data temporarily, but not more than 30 days and the stored data must either be refreshed or deleted after 30 days

Screenshot of Youtube Email?: https://user-images.githubusercontent.com/55116398/88565399-89490f00-d002-11ea-8c5f-71ce39675cec.jpeg

**Comment by zacimac** [comment]
I don't think this can be caused by the package. Because AFAIK for them to contact you, you require an API key from the Google API Console **(I could be wrong though)**.
Are you using any other YouTube API packages in your app?
