### ISSUE TITLE
Can't play any song

### ISSUE THREAD

**Issue by Ironrescue** [amishshah/ytdl-core-discord#223]
i installed `npm i fs`, `npm i prism-media` and `npm i ffmpeg-static` 
i added this code in my workspace as well: `fs.createReadStream('./audio.ogg')
  .pipe(new prism.opus.OggDemuxer())
  .pipe(new prism.opus.Decoder({ rate: 48000, channels: 2, frameSize: 960 }))
  .pipe(fs.createWriteStream('./audio.pcm'));`
and also :
`async function play(connection, url) {
  connection.play(await ytdl(url), { type: 'opus' });` 
but it doesn't run and the errors I get is "UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received an instance of Object"

before I installed ytdl-core-discord everything was working well

**Comment by amishshah** [comment]
`url` is not a string. Please debug this and make sure you're passing in correct data to the ytdl function.
