### ISSUE TITLE
Error: Could not find player config

### ISSUE THREAD

**Issue by TheMasterMuff** [amishshah/ytdl-core-discord#232]
I'm trying to make a discord music bot, it works good but sometimes, when i try to play some songs it automatically ends the song and throws this error.

`Error: Could not find player config`

I tried reinstalling the package but i still get the same error, any solutions?

**Comment by Vothm** [comment]
I had this error recently, I found out that I got this error whenever I tried to play a private video or if it was unavailable in my country.
Therefore I just enclosed it in a try catch statement and then doing .shift() on my playlist queue and skipping to the next music. If the video is unavailable it will go in the catch statement and get the error and skip to the next song

**Comment by SugarD-x** [comment]
I'm getting this on every video now, as well. I upgraded from version 3.1.0 to version 3.2.2. It looks like it might be related to the path change in the "ytdl-core" project in ```/lib/info.js``` on line 87. It doesn't look like this project has updated its path to match.

**Comment by Void0Alex** [comment]
The error has been fixed in the latest version of ytdl-core, but the author of this package (ytdl-core-discord) hasn't updated it to use the latest version of ytdl-core. Best you could do for now is what Vothm said (catch the error and handle it however you'd like)

**Comment by amishshah** [comment]
Will update this today.

**Comment by amishshah** [comment]
Sorry, I made the fix the same day but just forgot about actually releasing it! I've released it today under `prism-media@1.2.2`. Hopefully it fixes your issues; if not, feel free to re-open this issue :heart:
