### ISSUE TITLE
Bug: Error during playback

### ISSUE THREAD

**Issue by bartixen** [amishshah/ytdl-core-discord#252]
Describe the bug
`The error is that everything works great on my computer, but on vps I get this error with the song, e.g. https://www.youtube.com/watch?v=SXFS1-BEtaQ The problem is with ytdl-core and ytdl-core-discord`

Works on: `VPS` | `1 CORE` | `2 GB RAM`

Node.js version: `v12.19.0`

Debian version: `4.9.228-1`

Additional information & screenshots
![95331501-6365a380-08aa-11eb-9b69-4feef6851255](https://user-images.githubusercontent.com/48735544/95429312-7fb91d00-094a-11eb-8b1d-3bf7e1635e2e.png)

**Comment by fdciabdul** [comment]
Blocked rate limit by youtube itself

**Comment by amishshah** [comment]
@bartixen are you unable to play the song with `ytdl-core` itself? If so, this is more of an issue for their repo instead of this one.
