### ISSUE TITLE
chore: update ytdl-core to v3.4.2

### ISSUE THREAD

**Issue by jennasisis** [amishshah/ytdl-core-discord#259]
[ytdl-core 3.4.2](https://github.com/fent/node-ytdl-core/releases/tag/v3.4.2) was released a few hours ago. 
This release fixes two issues I was having, see https://github.com/fent/node-ytdl-core/issues/735 and https://github.com/fent/node-ytdl-core/issues/736

**Comment by amishshah** [comment]
Done, released in [v1.2.4](https://github.com/amishshah/ytdl-core-discord/releases/tag/v1.2.4)
