### ISSUE TITLE
Error: No suitable format found

### ISSUE THREAD

**Issue by dylanjamesdev** [amishshah/ytdl-core-discord#266]
Hi there :)

Not sure if you can help, but I'm getting this error and I don't believe it's a rate limit by youtube because I have not met my API usage quota. Any info would be appreciated, best wishes.

<img width="762" alt="Screen Shot 2020-10-26 at 9 03 48 PM" src="https://user-images.githubusercontent.com/55116398/97244391-fa998900-17ce-11eb-86ea-97c59bc5dfd9.png">

**Comment by baileyherbert** [comment]
@amishshah can you merge #296 to fix this? ytdl-core is broken on 3.x versions.

**Comment by amishshah** [comment]
Resolved in the latest release!
