### ISSUE TITLE
Cant change volume for Dispatcher..

### ISSUE THREAD

**Issue by SahajSatish** [amishshah/ytdl-core-discord#35]
I checked out https://github.com/amishshah/ytdl-core-discord/issues/5
I saw the way to set the volume using dispatcher using playConvertedStream...but it didnt work
Error TypeError: Cannot read property 'Decoder' of undefined
Code
`
bot.play = async (guild, music) => {
let queue = bot.queue.get(guild.id);
let votes = bot.votes.get(guild.id)
let input = await ytdl(music.url)
let pcm = input.pipe(new prism.opus.Decoder({ rate: 48000, channels: 2, frameSize: 960 }));
if (!music) {
queue.voiceChannel.leave();
bot.queue.delete(guild.id);
bot.votes.delete(guild.id);
return queue.textChannel.send("🎵 Music playback has ended");
}

    let dispatcher = queue.playConvertedStream(pcm, { highWaterMark : 1<<25 })
        .on('end', () => {
            queue.musics.shift();
            votes.votes = 0;
            votes.voters = [];
            setTimeout(() => {
                bot.play(guild, queue.musics[0]);
            }, 250);
        })
        .on('error', err => console.error(err));
    dispatcher.setVolumeLogarithmic(queue.volume / 100);

    queue.textChannel.send("🎵 **${music.title}** is now being played");
}`

**Comment by SahajSatish** [comment]
figured it out, pl close this issue

**Comment by Taha-Chaudhry** [comment]
may i ask how you fixed this issue? im having the same problem
