### ISSUE TITLE
Support for DiscordJS V13

### ISSUE THREAD

**Issue by benniblot** [amishshah/ytdl-core-discord#391]
Hey, thank you for creating this wonderful peace of code. I started to use ytdl-core-discord instead of ytdl-core because it worked much better especially with live videos. Now after they updated discordjs ytdl-core-discord doesnt work anymore so im kindly asking you to please update it.

Thank,
Benni

**Comment by LehuyH** [comment]
It still works in v13. 

Check #392 

You need to install correctly `@discordjs/voice` and get a connection using `joinVoiceChannel`

**Comment by Benni0109** [comment]
Thanks for your answer but when I try to use ytdl-core-discord it doesnt play music but when I play music using the normal ytdl it plays. Maybe you could say me whats the problem with it.

My log from the Bot:
PS D:\GitHub\BenniBot> node .
BenniBot#8620 Version 4.0.0.0 started sucessfully!
Connection transitioned from ready to ready
Audio player transitioned from idle to buffering
[15-09-2021 14:53:34] [Servername]: playing - lofi hip hop radio - beats to relax/study to
Connection transitioned from ready to disconnected
PS D:\GitHub\BenniBot> node .
BenniBot#8620 Version 4.0.0.0 started sucessfully!
Connection transitioned from signalling to signalling
Audio player transitioned from idle to buffering
[15-09-2021 14:54:07] [Servername]: playing - lofi hip hop radio - beats to relax/study to
Connection transitioned from signalling to connecting
Connection transitioned from connecting to connecting
Connection transitioned from connecting to connecting
Connection transitioned from connecting to connecting
Connection transitioned from connecting to ready
Audio player transitioned from buffering to playing
Audio player transitioned from playing to idle
[15-09-2021 14:54:13] [Servername]: Stopped playing Music and left the Voice Channel
Connection transitioned from ready to destroyed

**Comment by benniblot** [comment]
Thanks for your help, just fixed the problem in my code.

**Comment by lucasfp13** [comment]
@LehuyH @Benni0109 I tried to follow that #392 instructions but it's not working for me. Maybe you guys have a clue for what's happening here?

<img width="826" alt="Screen Shot 2021-09-19 at 20 13 27" src="https://user-images.githubusercontent.com/15722605/133945987-d4516b16-03a5-475c-aec4-5781a7182e85.png">

**Comment by benniblot** [comment]
Hey could you quickly explain what works and what doesnt? (e.g. does it join the voice channel, ...)

**Comment by lucasfp13** [comment]
@Benni0109 right now it joins in the voice channel, send the message reply just fine, but no audio from Bot. I even checked these player events, the player goes to 'Playing' state but right after goes to the 'AutoPause' state and nothing plays on Discord

**Comment by benniblot** [comment]
Could you maybe send me the log from the states? (If you want we could connect via discord so we don't spam this issue)
It should look something like this when it works:
Audio player transitioned from buffering to playing
Audio player transitioned from playing to autopaused
Connection transitioned from signalling to connecting
Connection transitioned from connecting to connecting
Connection transitioned from connecting to connecting
Connection transitioned from connecting to connecting
Connection transitioned from connecting to ready
Audio player transitioned from autopaused to playing
[Servername]: Stopped playing Music and left the Voice Channel
Connection transitioned from ready to destroyed
Audio player transitioned from playing to autopaused

**Comment by lucasfp13** [comment]
Here is the log. As you can see at the bottom I logged the AudioPlayer statuses and right after the "Playing" state it goes to the "AutoPaused"

![Screen Shot 2021-09-20 at 10 33 33](https://user-images.githubusercontent.com/15722605/134011203-56839f54-8b01-4a2f-aeb2-2956ea58c4f2.png)

**Comment by benniblot** [comment]
Just though about it and you could try to make an var instead of an const for stream.
Try this:		
var stream = await ytdl("youtube.com/????", {
				highWaterMark: 1 << 25,
				filter: 'audioonly',
});


This works for me: 
![image](https://user-images.githubusercontent.com/47495914/134040596-5964b41e-efee-47f8-bb0c-8c8f832669aa.png)

**Comment by lucasfp13** [comment]
@Benni0109 hey it worked!! Thanks a lot for the help 🙌🏼

**Comment by benniblot** [comment]
No Problem, have fun coding :)
