### ISSUE TITLE
Videos without opus encoding cause error.

### ISSUE THREAD

**Issue by Crow08** [amishshah/ytdl-core-discord#41]
When trying to process a video without opus encoding the `find` function on [line 15](https://github.com/amishshah/ytdl-core-discord/blob/c23636846fc2cc750d81f4ffcfecca26ee6dc595/index.js#L15) finds no match and sets `format` to `undefined`. Then the  `canDemux` flag is `false` and in [line 28](https://github.com/amishshah/ytdl-core-discord/blob/c23636846fc2cc750d81f4ffcfecca26ee6dc595/index.js#L28) `format.url` is accessed despite `format` being `undefined`.

Code and URL to reproduce this Error (Discord.js Version 12):
```JS
const ytdl = require('ytdl-core-discord');

async function play(connection, url) {
  connection.play(await ytdl('https://www.youtube.com/watch?v=hWlCv3VfePw'), { type: 'opus' });
}
```
Error log:
```
TypeError: Cannot read property 'url' of undefined
    at ytdl.getInfo ([..]\ytdl-core-discord\index.js:28:20)
    ...
```

**Comment by sudormr** [comment]
This seems to apply to vorbis only videos
