### ISSUE TITLE
Can't change volume from dispatcher

### ISSUE THREAD

**Issue by SchdowNVIDIA** [amishshah/ytdl-core-discord#5]
Since im using this lib i can't change the volume of the dispatcher. it was possible on ytdl-core.
i've already tried: 
dispatcher.setVolume(0.5);
dispatcher.setVolumeLogarithmic(0.5);
but nothing of it changes the volume.

**Comment by amishshah** [comment]
Are you using Discord.js v11.4.2 or v12 (master branch)

**Comment by SchdowNVIDIA** [comment]
I'm using 11.4.2 and what is the volume there? rate?

**Comment by SchdowNVIDIA** [comment]
Well i mean on the normal ytdl-core it works
![image](https://user-images.githubusercontent.com/39440218/53286111-eedc0080-3769-11e9-8a5d-69b81b5472e8.png)

**Comment by amishshah** [comment]
For Discord.js v11.4.2, the documentation states that inline volume is not compatible for opus streams -- [see here.](https://discord.js.org/#/docs/main/stable/class/VoiceConnection?scrollTo=playOpusStream)

A workaround is possible using [`prism-media`](https://hydrabolt.me/prism-media/) (`npm install prism-media` or `yarn add prism-media`):

```js
const ytdl = require('ytdl-core-discord');
const prism = require('prism-media');

async function play(url) {
  const stream = await ytdl(url)
    .pipe(new prism.opus.Decoder({ rate: 48000, channels: 2, frameSize: 960 }))

  const dispatcher = connection.playConvertedStream(stream);
}
```

**Comment by amishshah** [comment]
Yes it might work with normal ytdl-core, but this module improves performance when using `playOpusStream` or using the method shown above.

The above code example should allow you to keep performance improvements while also being able to change the volume.

**Comment by SchdowNVIDIA** [comment]
Okay, i test it out

**Comment by SchdowNVIDIA** [comment]
I'm getting an error. 
![image](https://user-images.githubusercontent.com/39440218/53286181-c1dc1d80-376a-11e9-998f-4fd715f149cb.png)

**Comment by amishshah** [comment]
it's playConvertedStream

**Comment by SchdowNVIDIA** [comment]
Code:
    const dispatcher = serverQueue.connection.playConvertStream(pcm)
		.once('end', reason => {
			if (reason === 'Stream is not generating quickly enough.') console.log('Song ended.');
			else console.log(reason);
			serverQueue.songs.shift();
			play(guild, serverQueue.songs[0]);
		})
        .on('error', error => console.error(error));

**Comment by SchdowNVIDIA** [comment]
Oh okay

**Comment by SchdowNVIDIA** [comment]
Works now fine but i'm not sure if the quality is still the same.

**Comment by SchdowNVIDIA** [comment]
Well quality is now bad... i think i just wait until you guys add a function to set the volume.

**Comment by SchdowNVIDIA** [comment]
Okay, now the quality is good again thank you for helping me out! i think that was a problem on my server

**Comment by amishshah** [comment]
No problem!

Glad it works for you.

**Comment by SahajSatish** [comment]
Error `TypeError: Cannot read property 'Decoder' of undefined`
Code
`    bot.play = async (guild, music) => {
        let queue = bot.queue.get(guild.id);
        let votes = bot.votes.get(guild.id)
        let input = await ytdl(music.url)
        let pcm = input.pipe(new prism.opus.Decoder({ rate: 48000, channels: 2, frameSize: 960 }));
        if (!music) {
            queue.voiceChannel.leave();
            bot.queue.delete(guild.id);
            bot.votes.delete(guild.id);
            return queue.textChannel.send(`🎵 Music playback has ended`);
        }

        let dispatcher = queue.playConvertedStream(pcm, { hightWaterMark : 10<<250 })
            .on('end', () => {
                queue.musics.shift();
                votes.votes = 0;
                votes.voters = [];
                setTimeout(() => {
                    bot.play(guild, queue.musics[0]);
                }, 250);
            })
            .on('error', err => console.error(err));
        dispatcher.setVolumeLogarithmic(queue.volume / 100);

        queue.textChannel.send(`🎵 **${music.title}** is now being played`);
    }`
