### ISSUE TITLE
The song stop in the middle of nowhere.

### ISSUE THREAD

**Issue by conver4y** [amishshah/ytdl-core-discord#6]
Playing some live streams, and after 15 - 30 (or above) minutes, it stopped in the 'middle of nowhere'. Not leaving the channel, but stopped.

**Comment by SirDeadlystrike** [comment]
This is likely related to: https://github.com/fent/node-ytdl-core/issues/402

**Comment by Ensjam** [comment]
Same issue

**Comment by Sirboys** [comment]
I use this packages:

>     "discord.js": "11.4.2",
 >   "fs": "0.0.1-security",
>	"ffmpeg-static": "2.4.0",
>	"ffmpeg-binaries":"4.0.0",
>    "node-opus": "github:Rantanen/node-opus#master",
>    "simple-youtube-api": "^3.0.0",
>    "ytdl-core": "github:fent/node-ytdl-core#master",
>    "ytdl-core-discord": "github:amishshah/ytdl-core-discord#master"

**Comment by TheeJoshhh** [comment]
I'm getting the same issue, sometimes I make it through a song but most of the time it disconnects in the middle. Is there something I can do on my end to fix it? Could the error be in my code?

**Comment by amishshah** [comment]
Can you try installing master branch and seeing if the issue persists? `npm install amishshah/ytdl-core-discord`.

I made a change that should hopefully fix it! Also, if possible could you give me example videos that this issue occurs on?

**Comment by TheeJoshhh** [comment]
Sorry for slow reply, been busy with exams. I'll try that when I get a chance and see if it fixes it. I can't give you a video cause it doesn't happen often but I can explain it in more detail. The bot will just leave the voice channel and act as if the song had finished playing e.g it sends a message saying "Finished playing queue" in the chat.

**Comment by saanuregh** [comment]
Dispatcher on 'end' event doesnt occur, it just stops playback in middle of the song. The bot remains in the voice channel. Also i noticed that it happens way more often when running bot on my laptop than hosted.

**Comment by TheeJoshhh** [comment]
I am still having same issue after installing master branch.

**Comment by saanuregh** [comment]
@TheeJoshhh i noticed that you get "Finished playing queue" in the chat, that means for you dispatcher on 'end' happens, right? Also just following a hunch, how do you run the bot?

**Comment by TheeJoshhh** [comment]
Yes it does run the end event but usually when the end event is run it plays the next song in queue, in this case it just commits die. I host on a Unbuntu VPS if that's what you were asking?

**Comment by PropreCity** [comment]
Same problem for me. The sound stops 15 / 30s before its end. Sometimes it doesn't happen, but it's really rare.

**Comment by saanuregh** [comment]
this might help....hard to test since stream ending prematurely happens very rarely
highWaterMark: 1

**Comment by ZeroGl1tch** [comment]
Can confirm that using the `highWaterMark: 1<<25` option fixes the problem. The same is suggested in this issue:  https://github.com/fent/node-ytdl-core/issues/402 . I have tried various songs of different length multiple times to test this and its consistent.

**Comment by reisdev** [comment]
> Can confirm that using the `highWaterMark: 1<<25` option fixes the problem. The same is suggested in this issue:  https://github.com/fent/node-ytdl-core/issues/402 . I have tried various songs of different length multiple times to test this and its consistent.
> 
> my code (discord.js v12) :
>  `const dispacther = connection.play(await ytdl(url, {highWaterMark: 1<<25}), {type: 'opus'});

Which node version are you using?

**Comment by Taha-Chaudhry** [comment]
problem not fixed @ZeroGl1tch

**Comment by PropreCity** [comment]
It works for me :
```js
connection.play(await ytdl(url, {
    filter: format => ['251'],
    highWaterMark: 1 << 25
}), {
    type: 'opus'
});
```

**Comment by inhydrox** [comment]
I use eris I was also getting same issues I used `highWaterMark: 1 << 25`, and the issue solved

**Comment by advaith1** [comment]
Should be fixed after the ytdl-core version being used is updated due to https://github.com/fent/node-ytdl-core/commit/f4a9b65

**Comment by amishshah** [comment]
I am going to close this issue as I'm now using the latest version of ytdl-core in this module. If anyone still experiences this, then please create a new issue which I will try to track more actively!

**Comment by tycrek** [comment]
> I am going to close this issue as I'm now using the latest version of ytdl-core in this module. If anyone still experiences this, then please create a new issue which I will try to track more actively!

Do you know if we still require the `highWaterMark` flag?

**Comment by North-West-Wind** [comment]
You better keep it. It helps you to reduce lag
