### ISSUE TITLE
“Cannot read property ‘send’ of undefined”?

### ISSUE THREAD

**Issue by Lightningrod6** [amishshah/ytdl-core-discord#87]
For some reason ‘send’ is undefined and i’ve spent a good 2 hours trying to find out why

https://hatebin.com/zgaqbismui

https://hatebin.com/mzgbqhqecy

**Comment by Dmitry221060** [comment]
@amishshah Same problem. For some reason, `module.exports = Object.assign(download, ytdl);` doesn't work properly and `download` doesn't contain anything from `ytdl`

**Comment by amishshah** [comment]
I think this is now fixed.
