### ISSUE TITLE
Some videos do not play

### ISSUE THREAD

**Issue by Sirboys** [amishshah/ytdl-core-discord#9]
I tryed listen this video: https://www.youtube.com/watch?v=tkWxJS52yKA
Bot crashed.
![screenshot_108](https://user-images.githubusercontent.com/35031222/53941759-c5f92b00-40da-11e9-9d44-a452a7c918d9.png)

**Comment by amishshah** [comment]
Can you try installing ffmpeg-static instead of ffmpeg-binaries?

**Comment by Sirboys** [comment]
It's work thanks ;)
